In [ ]:
#Name:Shricharan
#Register Number - 125013036
#Date-24/02/2024
#BIN2023R01 - INTRODUCTION TO DATAMINING & MACHINE LEARNING FOR BIOINFORMATICS
#Exercise5
#Version - 1.0

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('kc_house_data.csv')
dataset

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [ ]:
dataset = pd.read_csv("kc_house_data.csv")

dependent_variable = dataset.pop("price")
independent_variables = dataset

correlations = independent_variables.corrwith(dependent_variable)

threshold = 0.6

significant_variables = correlations[abs(correlations) > threshold].index

selected_data = dataset[significant_variables]

print(significant_variables)

Index(['sqft_living', 'grade', 'sqft_above'], dtype='object')

<ipython-input-105-f1aae6abd21e>:6: FutureWarning: The default value of numeric_only in DataFrame.corrwith is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlations = independent_variables.corrwith(dependent_variable)

In [ ]:
selected_data

       sqft_living  grade  sqft_above
0             1180      7        1180
1             2570      7        2170
2              770      6         770
3             1960      7        1050
4             1680      8        1680
...            ...    ...         ...
21608         1530      8        1530
21609         2310      8        2310
21610         1020      7        1020
21611         1600      8        1600
21612         1020      7        1020

[21613 rows x 3 columns]

In [ ]:
print(dataset.isnull().sum())

id               0
date             0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [ ]:
from scipy import stats

combined_dataset = np.column_stack((selected_data,dependent_variable))

z_scores_combined = np.abs(stats.zscore(combined_dataset))

threshold = 3

cleaned_dataset = combined_dataset[(z_scores_combined < threshold).all(axis=1)]

cleaned_selected_data = cleaned_dataset[:, :-1]
cleaned_dependent_variable = cleaned_dataset[:, -1]

In [ ]:
cleaned_selected_data

array([[1180.,    7., 1180.],
       [2570.,    7., 2170.],
       [ 770.,    6.,  770.],
       ...,
       [1020.,    7., 1020.],
       [1600.,    8., 1600.],
       [1020.,    7., 1020.]])

In [ ]:
cleaned_dependent_variable

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler_standardization = StandardScaler()
selected_data_standardized = scaler_standardization.fit_transform(cleaned_selected_data)
selected_data_standardized

array([[-1.05664299, -0.54655579, -0.75493832],
       [ 0.72631316, -0.54655579,  0.61346306],
       [-1.58255091, -1.48932292, -1.32165001],
       ...,
       [-1.26187535, -0.54655579, -0.9760941 ],
       [-0.51790803,  0.39621135, -0.1744044 ],
       [-1.26187535, -0.54655579, -0.9760941 ]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler_standardization_dep = StandardScaler()
dependent_variable_standardized = scaler_standardization_dep.fit_transform(cleaned_dependent_variable.reshape(-1, 1))
dependent_variable_standardized

array([[-1.11465233],
       [ 0.14984577],
       [-1.28226534],
       ...,
       [-0.39379241],
       [-0.40219706],
       [-0.70222034]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(selected_data_standardized, dependent_variable_standardized, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (16770, 3)
X_test shape: (4193, 3)
y_train shape: (16770, 1)
y_test shape: (4193, 1)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [[ 0.50172939  0.4400282  -0.20905222]]
Intercept: [0.00596911]

In [ ]:
y_test_1d = y_test.ravel()
y_pred_1d = y_pred.ravel()

reg_model_diff = pd.DataFrame({'Actual value': y_test_1d, 'Predicted value': y_pred_1d})
print(reg_model_diff)

      Actual value  Predicted value
0        -0.114175        -0.408275
1         1.229930         0.375033
2         0.437868         0.211858
3        -1.284265        -0.606858
4        -1.490281        -1.092625
...            ...              ...
4188      0.377863         0.293805
4189     -1.496282        -1.039433
4190     -1.378273        -1.642222
4191     -1.062248        -0.364303
4192     -0.322191         0.599573

[4193 rows x 2 columns]

In [ ]:
from sklearn import metrics
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
r2 = np.sqrt(metrics.mean_squared_error(y_test, y_pred))

print('Mean Absolute Error:', mae)
print('Mean Square Error:', mse)
print('Root Mean Square Error:', r2)

Mean Absolute Error: 0.5352963265412918
Mean Square Error: 0.5064314591443789
Root Mean Square Error: 0.7116399786018061